repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.1.1
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: gofmt
      - id: goimports
      - id: golint
